/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jmabuin_metacachespark_database_MapNative */

#ifndef _Included_com_github_jmabuin_metacachespark_database_MapNative
#define _Included_com_github_jmabuin_metacachespark_database_MapNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_init
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    add
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_add
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    addAll
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_addAll
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    get
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_get
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    get_best
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_get_1best
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    get_by_pos
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_get_1by_1pos
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_size
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    resetIterator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_resetIterator
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    get_current
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_get_1current
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_next
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    isEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_isEnd
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    resetFSTIterator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_resetFSTIterator
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    resetLSTIterator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_resetLSTIterator
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    get_currentFST
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_get_1currentFST
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    get_currentLST
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_get_1currentLST
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    nextFST
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_nextFST
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    nextLST
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_nextLST
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    isEndFST
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_isEndFST
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    isEndLST
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_isEndLST
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_database_MapNative
 * Method:    setFST2LST
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_database_MapNative_setFST2LST
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
