/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_metacachespark_HashFunctions */

#ifndef _Included_com_github_metacachespark_HashFunctions
#define _Included_com_github_metacachespark_HashFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    make_reverse_complement64
 * Signature: (JI)I
 */
JNIEXPORT jlong JNICALL Java_com_github_metacachespark_HashFunctions_make_1reverse_1complement64
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    make_reverse_complement32
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_metacachespark_HashFunctions_make_1reverse_1complement32
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
