/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_metacachespark_HashFunctions */

#ifndef _Included_com_github_metacachespark_HashFunctions
#define _Included_com_github_metacachespark_HashFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    make_reverse_complement64
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_metacachespark_HashFunctions_make_1reverse_1complement64
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    make_reverse_complement32
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_metacachespark_HashFunctions_make_1reverse_1complement32
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    thomas_mueller_hash32
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_metacachespark_HashFunctions_thomas_1mueller_1hash32
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    kmer2uint32
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_metacachespark_HashFunctions_kmer2uint32
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_metacachespark_HashFunctions
 * Method:    window2sketch32
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_metacachespark_HashFunctions_window2sketch32
  (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT jintArray JNICALL Java_com_github_metacachespark_HashFunctions_sequence2features
  (JNIEnv *, jclass, jstring, jint, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
