/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2 */

#ifndef _Included_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
#define _Included_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    next
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_next
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    total
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_total
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    current
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_current
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    skip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_skip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    get_header
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_get_1header
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    get_data
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_get_1data
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    get_quality
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_get_1quality
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jmabuin_metacachespark_io_SequenceFileReaderNative2_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
