/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jmabuin_metacachespark_io_ExtractionFunctions */

#ifndef _Included_com_github_jmabuin_metacachespark_io_ExtractionFunctions
#define _Included_com_github_jmabuin_metacachespark_io_ExtractionFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jmabuin_metacachespark_io_ExtractionFunctions
 * Method:    extract_ncbi_accession_version_number
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_ExtractionFunctions_extract_1ncbi_1accession_1version_1number
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_jmabuin_metacachespark_io_ExtractionFunctions
 * Method:    extract_genbank_identifier
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_ExtractionFunctions_extract_1genbank_1identifier
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_jmabuin_metacachespark_io_ExtractionFunctions
 * Method:    extract_ncbi_accession_number
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jmabuin_metacachespark_io_ExtractionFunctions_extract_1ncbi_1accession_1number
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_jmabuin_metacachespark_io_ExtractionFunctions
 * Method:    extract_taxon_id
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jmabuin_metacachespark_io_ExtractionFunctions_extract_1taxon_1id
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
