/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jmabuin_metacachespark_LocationsSortedList */

#ifndef _Included_com_github_jmabuin_metacachespark_LocationsSortedList
#define _Included_com_github_jmabuin_metacachespark_LocationsSortedList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jmabuin_metacachespark_LocationsSortedList
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_LocationsSortedList_init
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jmabuin_metacachespark_LocationsSortedList
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_LocationsSortedList_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_jmabuin_metacachespark_LocationsSortedList
 * Method:    get
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_jmabuin_metacachespark_LocationsSortedList_get
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_jmabuin_metacachespark_LocationsSortedList
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_jmabuin_metacachespark_LocationsSortedList_size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
